name: Docs - Publier PDFs

on:
  push:
    paths:
      - "doc/**"
      - ".github/workflows/docs.yml"
  pull_request:
    paths:
      - "doc/**"
      - ".github/workflows/docs.yml"

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lister le contenu de doc/
        run: |
          echo "Contenu de doc/ :"
          ls -R doc

      - name: Upload UserGuide & ProgrammerGuide PDFs
        uses: actions/upload-artifact@v4
        with:
          name: guides-pdf
          path: |
            doc/UserGuide/PDF/UserGuide.pdf
            doc/ProgrammerGuide/PDF/ProgrammerGuide.pdf
          if-no-files-found: ignore
